In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[8]
#get array value from index

8

In [4]:
arr[0:5]
#get array value from kjarak index

array([0, 1, 2, 3, 4])

In [5]:
arr[0] = 9
arr
#merubah array numpy

array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[0:5] = 9
arr

array([9, 9, 9, 9, 9, 5, 6, 7, 8, 9])

In [7]:
data = arr[0:5]
data
#array dari index 0-5

array([9, 9, 9, 9, 9])

In [8]:
data[:] = 99
data
#merubah semua data array

array([99, 99, 99, 99, 99])

In [9]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [10]:
newData = arr.copy()
newData
#duplikasi data array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [11]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,30,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 30, 45]])

In [12]:
arr_2d[1]

array([20, 25, 30])

In [13]:
arr_2d[2][1]

30

In [14]:
arr_2d[1][2]

30

In [15]:
arr_2d[2,2]
#untuk aray skala kecil, tidak direkomendasikan

45

In [16]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [18]:
nilai = np.arange(1,11)
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
nilai > 5
#seleksi data array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
nilai[nilai > 5]

array([ 6,  7,  8,  9, 10])

In [21]:
nilai + nilai

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])